### PR TITLE
Add option to enable/disable camera controls on the outer ring

### PR DESCRIPTION
**Pull request by KristopherWagner**
I also ran js-beautify, that's probably why it looks like there are so many changes...

### CODE REVIEW

**Comment by alberto-acevedo** [comment]
Kristopher,

I just tested and it looks good. Thanks for your sharing.

Alberto

**Comment by KristopherWagner** [comment]
Alberto,

Do you plan to push a release for this? Or are you going to wait until there are more changes?

**Comment by alberto-acevedo** [comment]
Kristopher,

Sorry for the late reply. I didn't see your email. Yes I was waiting for more changes to come in. I'm releasing today a version with your contribution.

Thanks

**Comment by KristopherWagner** [comment]
Alberto,

I saw that you released v1.1.4 and credited me to the changes but it doesn't look like my changes are actually in the release? [v1.1.4](https://github.com/alberto-acevedo/cesium-navigation/commits/v1.1.4) [development](https://github.com/alberto-acevedo/cesium-navigation/commits/development)

**Comment by KristopherWagner** [comment]
bump

**Pull request merged**
